# Generated by Django 4.0.3 on 2022-04-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_profile_follower_profile_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ManyToManyField(to='network.profile'),
        ),
    ]
