# Generated by Django 4.0.4 on 2022-05-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_user_remove_post_profile_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers',
            new_name='followed_by',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user',
            new_name='followed_by',
        ),
    ]
