# Generated by Django 4.0.4 on 2022-05-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_followers_follower_followed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
