# Generated by Django 4.0.4 on 2022-05-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_profile_follower_delete_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='following',
            name='profile',
            field=models.ManyToManyField(to='network.profile'),
        ),
    ]
