# Generated by Django 4.0.4 on 2022-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_post_following_posts_alter_post_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='following',
            field=models.ManyToManyField(to='network.following'),
        ),
    ]
