# Generated by Django 4.0.4 on 2022-05-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_post_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='following',
        ),
    ]
